### PR TITLE
Add support for gcloud-python 0.4

### PR DESCRIPTION
**Pull request by rstuart85**
Made sure all code meets pep8 and updated the tests. Also removed code that is no longer needed.

Unfortunately, there doesn't seem to be an easy way to test insert anymore. The protobuf hooks into gcloud are very deep.

### CODE REVIEW

**Comment by rstuart85** [comment]
Unfortunately gcloud has changed how it does dataset_id detection. It needs to be set via environment variables before the tests are run. I could hardcode that into the tests if you like?

**Comment by lucemia** [comment]
Sure please, 
btw since gcloud 0.4 change so much, I will create another branch to merge your pull request.

**Comment by rstuart85** [comment]
I'm still finding bugs as I am using this in one of our products. I'll update it when I have it fully working.

Do you have any ideas on how we might test the insert functionality?

**Comment by lucemia** [comment]
> Do you have any ideas on how we might test the insert functionality?
> Let me take a look tomorrow  :)

**Comment by rstuart85** [comment]
I'm now using this code in a product and it is working well. It is lacking features around query (the filter method needs expanding upon) but the only thing stoping this pull request in my eyes is the tests.

**Comment by lucemia** [comment]
@rstuart85

I didn't see any test error especially for `Insert`. 
please correct me if I am wrong.  
The Test error message here looks like:

```

======================================================================
ERROR: testTimeProperty (test_properties.TestProperties)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/repos/gcloud-python-orm/tests/test_properties.py", line 156, in testTimeProperty
    m = TestModel()
  File "/Users/david/repos/gcloud-python-orm/gcloudorm/model.py", line 101, in __init__
    setattr(self, attr, getattr(self, attr))
AttributeError: 'TestModel' object has no attribute 'id'

----------------------------------------------------------------------
Ran 12 tests in 0.980s

FAILED (errors=11)
```

Two questions:
1. `StringProperty` is gone, what is the reason?
2. What is the purpose for `IdProperty`? The original ndb doesn't have the `IdProperty` either.

**Comment by rstuart85** [comment]
@lucemia 

Updated the tests so they work besides the insert test.

> 1. StringProperty is gone, what is the reason?

Unless I misunderstood, String property is exactly the same as BlobProperty except it has no compression option. It seemed redundant.

> 1. What is the purpose for IdProperty? The original ndb doesn't have the IdProperty either.

Having to explicitly pass an id to a model instance when creating it was annoying and not how Django works. Also, the method of accessing the key and hence id_or_name has changed in gcloud-python. Allowing you to specify which property is the id or have one auto injected matches the existing Django ORM behaviour and is in my opinion much nicer because it makes it clear which property is the id and how to access it is obvious.

**Comment by lucemia** [comment]
@rstuart85 
1. The `StringProperty` is important to compatible with ndb, and my company use it a lot. So I cannot delete it.
2. The same reason as above, but I think it is possible to accept the `IdProperty` as an alternative approach. Just need time to mix it and test it.
3. This pull request currently mix a lot of changes. It will be much easier to create a new branch first and split your pull request to several minor pull request. Unlucky, I didn't find a way to work on it (ex: push to your pull request) easily with github.

If you agree, I will start to work on it today.

**Comment by rstuart85** [comment]
@lucemia Sounds good.

**Pull request closed without merging**
